name: Check Deploy Status

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  check_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check last deploy status
      if: env.SUBMODULE_STATUS == 'false'
      id: check-deploy-status
      run: |
          latest_run_url=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/runs" | \
            jq -r '.workflow_runs[0].conclusion')
          
          echo "Latest deploy conclusion: $latest_run_url"
          
          if [ "$latest_run_url" == "failure" ]; then
            echo "Previous Deploy workflow failed, triggering a retry..."
            echo "deploy_retry_needed=true" >> $GITHUB_ENV
          else
            echo "Deploy workflow succeeded or was canceled."
            echo "deploy_retry_needed=false" >> $GITHUB_ENV
          fi
          
    - name: Trigger workflow if previous run failed
      if: env.deploy_retry_needed == 'true'
      run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "update-assets"}'
