name: Check Submodule Updates

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
permissions:
  contents: write
  actions: write
jobs:
  check_submodule_update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 1
        token: ${{ secrets.ASSET_REPO_TOKEN }}

    - name: Check for updates in submodules' main branch
      run: |
        echo "Checking submodules..."
        UPDATED=false
        for submodule in $(git config --file .gitmodules --get-regexp path | awk '{print $2}'); do
          url=$(git config --file .gitmodules --get-regexp "submodule.$submodule.url" | awk '{print $2}')
          echo "Checking submodule: $submodule"
          export GIT_ASKPASS=$(mktemp)
          echo "echo '${{ secrets.ASSET_REPO_TOKEN }}'" > $GIT_ASKPASS
          chmod +x $GIT_ASKPASS
          current=$(git rev-parse HEAD:$submodule)
          latest=$(git ls-remote "$url" refs/heads/main | awk '{print $1}')
          rm -f $GIT_ASKPASS  # Cleanup auth helper
          echo "'$submodule': Current commit: $current, Latest commit: $latest"
          if [ "$current" != "$latest" ]; then
            echo "Submodule '$submodule' has an update."
            UPDATED=true
          else
            echo "No update for submodule '$submodule'."
          fi
        done
        echo "SUBMODULE_STATUS=$UPDATED" >> $GITHUB_ENV

    - name: Trigger follow-up workflow if update detected
      if: env.SUBMODULE_STATUS == 'true'
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "update-assets"}'