name: Check Submodule Updates

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
permissions:
  contents: write
  actions: write
jobs:
  check_submodule_update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 1
        token: ${{ secrets.ASSET_REPO_TOKEN }}

    - name: Check for updates in submodules' main branch
      run: |
        UPDATED=false
        for submodule in $(git config --file .gitmodules --get-regexp path | awk '{print $2}'); do
          echo "Checking submodule: $submodule"
          cd "$submodule"
          
          git fetch --depth 1 origin main
          
          current=$(git rev-parse HEAD)
          latest=$(git rev-parse origin/main)
          
          if [ "$current" != "$latest" ]; then
            echo "Submodule '$submodule' has an update."
            UPDATED=true
          else
            echo "No update for submodule '$submodule'."
          fi
          cd - > /dev/null
        done
        echo "SUBMODULE_STATUS=$UPDATED" >> $GITHUB_ENV

    - name: Trigger follow-up workflow if update detected
      if: env.SUBMODULE_STATUS == 'true'
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "update-assets"}'